chore(apps/interface): update open graph image
risedle/monorepo pull request #153
Opened 2022-07-25 03:47 UTC by math-marcellino

Update open graph image (RIS-528)

2022-07-25 04:43 UTC, risedledev requested changes

2022-07-25 04:43 UTC, risedledev commented on apps/interface/pages/_app.tsx
> +                            url: "/opengraph/LandingBSC.png",
- Use full path for opengraph url
- Use template based string
- rename file to the following format `public/opengraph/$page-$chainslug.png`

For example:

Filenames:
-  `public/opengraph/landing-bsc.png`
- `public/opengraph/portfolio-bsc.png`
- `public/opengraph/trade-bsc.png`

then use it as below:

```typescript
url: `https://${chainSlug}.risedle.com/opengraph/landing-${chainSlug}.png",
```

you can get `chainSlug` from https://github.com/risedle/monorepo/blob/b4f3bd8a9f1cb44535076c4997179a9d788000a9/apps/interface/utils/getBaseConfig.ts#L41-L45

for example:

```
const { chainSlug } = getBaseConfig();
```

2022-07-25 04:44 UTC, pyk requested changes

2022-07-25 04:44 UTC, pyk commented on apps/interface/pages/_app.tsx
> +                            url: "/opengraph/LandingBSC.png",
- Use full path for opengraph url
- Use template based string
- rename file to the following format `public/opengraph/$page-$chainslug.png`

For example:

Filenames:
-  `public/opengraph/landing-bsc.png`
- `public/opengraph/portfolio-bsc.png`
- `public/opengraph/trade-bsc.png`

then use it as below:

```typescript
url: `https://${chainSlug}.risedle.com/opengraph/landing-${chainSlug}.png",
```

you can get `chainSlug` from https://github.com/risedle/monorepo/blob/b4f3bd8a9f1cb44535076c4997179a9d788000a9/apps/interface/utils/getBaseConfig.ts#L41-L45

for example:

```
const { chainSlug } = getBaseConfig();
```

2022-07-25 04:50 UTC, math-marcellino commented on apps/interface/pages/_app.tsx
> +                            url: "/opengraph/LandingBSC.png",
Got it sir, I'll update it real soon 👍

2022-07-25 04:54 UTC, pyk commented on apps/interface/pages/_app.tsx
> +                            url: "/opengraph/LandingBSC.png",
@math-marcellino I think we need to use term `home-bsc.png` instead of `landing-bsc.png`

2022-07-25 04:55 UTC, math-marcellino commented on apps/interface/pages/_app.tsx
> +                            url: "/opengraph/LandingBSC.png",
Okay sir, I'll rename it to 👍

2022-07-25 04:58 UTC, math-marcellino commented on apps/interface/pages/_app.tsx
> +                            url: "/opengraph/LandingBSC.png",
Btw should we add the `arbitrum` og image to this repo too? @pyk

2022-07-25 05:05 UTC, pyk commented on apps/interface/pages/_app.tsx
> +                            url: "/opengraph/LandingBSC.png",
@math-marcellino yess lets go.

Btw we need to wait from ayik first about this

2022-07-25 10:19 UTC, pyk commented on apps/interface/pages/_app.tsx
> +                            url: "/opengraph/LandingBSC.png",
@math-marcellino ok ok, all looks good. Just need to wait for the image

2022-07-27 00:36 UTC, math-marcellino commented on apps/interface/pages/_app.tsx
> +                            url: "/opengraph/LandingBSC.png",
The opengraph images are updated sir 👍

2022-07-27 08:35 UTC, pyk approved these changes

2022-07-27 08:35 UTC, merged