chore(apps/interface): set timerame to align left on large screen
risedle/monorepo pull request #183
Opened 2022-07-27 12:53 UTC by math-marcellino

## Before
![image](https://user-images.githubusercontent.com/81855912/181251358-5bd5a81f-31d6-401c-917f-9b47da24b777.png)

## After
![image](https://user-images.githubusercontent.com/81855912/181251481-6c3ef4d3-0ed3-4a9c-80c4-97d364ad580e.png)

2022-07-27 13:43 UTC, pyk commented
This actually break the homepage

<img width="861" alt="Screen Shot 2022-07-27 at 20 09 26" src="https://user-images.githubusercontent.com/2213646/181254930-f9e264ed-1a17-4b21-af66-77931fe36ddb.png">

We can extends `BoxProps` in `PriceChartProps`:

https://github.com/risedle/monorepo/blob/12212308cf90e15f52062f18b9854d646d8da014/apps/interface/components/PriceChart/index.tsx#L13-L15

then pass this props:

```
display="flex"
justifyContent={{ base: "center", tablet: "start" }}
```

in trading page only

https://github.com/risedle/monorepo/blob/b0bc584db2c567192932697891260e43bd75510d/apps/interface/components/TradeInfoCard/index.tsx#L63-L64

2022-07-27 13:45 UTC, pyk requested changes
See my comment above

2022-07-27 16:31 UTC, pyk commented
> @pyk how about we create variant ? so we do not pass
> 
> ```
> display="flex"
> justifyContent={{ base: "center", tablet: "start" }}
> ```
> 
> but just variant maybe `homepage` or `detailToken`

I think it's more simple to pass the props, coz charts only used twice

2022-07-28 02:52 UTC, asaadam commented
@pyk okay let's use your approach

2022-07-28 08:23 UTC, math-marcellino commented
Sorry for the late reply, I've fixed it sir, please kindly check 👍 @pyk @asaadam

2022-07-28 08:35 UTC, pyk requested changes
All good, just need comment for docs

2022-07-28 08:35 UTC, pyk commented on apps/interface/components/TradeInfoCard/index.tsx
> +                display="flex"
Add comment above this line, something like "this styles is used to prevent timeframes to stretch"

2022-07-28 08:39 UTC, math-marcellino commented on apps/interface/components/TradeInfoCard/index.tsx
> +                display="flex"
Got it sir, fixed 👍

2022-07-28 08:46 UTC, risedledev approved these changes

2022-07-28 08:47 UTC, pyk approved these changes

2022-07-28 08:47 UTC, pyk commented
lol I use wrong account

2022-07-28 08:47 UTC, merged