feat(apps/interface): create my swap container
risedle/monorepo pull request #211
Opened 2022-07-30 11:45 UTC by asaadam

create my swap container

2022-08-01 04:46 UTC, pyk requested changes

2022-08-01 04:46 UTC, pyk commented on apps/interface/components/SwapHistoryCard/MySwapContainer.tsx
> +import type { FuseLeveragedTokenSwap } from "@/utils/types";
Add utils to its own group

```ts
// Utils
import type { FuseLeveragedTokenSwap } from "@/utils/types";

// Sub-components
...
```

2022-08-01 04:46 UTC, pyk commented on apps/interface/components/SwapHistoryCard/MySwapContainer.tsx
> +    timestamp: (new Date().getTime() / 1000).toString(),
just use dummy number here like `1659328398`

2022-08-01 04:46 UTC, pyk commented on apps/interface/components/SwapHistoryCard/MySwapContainer.tsx
> +        symbol: "",
Use dummy symbol `BNBRISE`

2022-08-01 04:46 UTC, pyk commented on apps/interface/components/SwapHistoryCard/MySwapContainer.tsx
> +        symbol: "",
Use dummy symbol `BUSD`

2022-08-01 04:46 UTC, pyk commented on apps/interface/components/SwapHistoryCard/MySwapContainer.tsx
> +        if (isLoaded && data) {
just use `if (data)`

2022-08-01 04:46 UTC, pyk commented on apps/interface/components/SwapHistoryCard/Table.tsx
> +                    {swaps.map((swap, index) => (
@asaadam nice addition 👍

2022-08-01 04:46 UTC, pyk commented on apps/interface/hooks/useFuseLeveragedTokenSwap.ts
> +// Get list of markets using SWR
typo here, it should be list of swaps

2022-08-01 04:46 UTC, pyk commented on apps/interface/hooks/useFuseLeveragedTokenSwap.ts
> +export function useFuseLeveragedTokenSwap(
I think we need to rename it to `useFuseLeveragedTokenMySwap`

2022-08-01 04:46 UTC, pyk commented on apps/interface/hooks/useFuseLeveragedTokenSwap.ts
> +    }
Set `url` to `null` if `userAddress` is null so swr doesn't perform the request when wallet is not connected.

Learn more here https://swr.vercel.app/docs/conditional-fetching

See example here https://github.com/risedle/monorepo/blob/733ae7b401ceed364151168d3237ed5bdcd54245/apps/interface/hooks/useFuseLeveragedTokenUserPosition.ts#L16-L22

2022-08-01 04:46 UTC, pyk commented on apps/interface/hooks/useFuseLeveragedTokenSwap.ts
> +        isLoaded: data?.user !== undefined ? true : false,
return loaded if data.user is not null or `userAddress` is null.

See example here:

https://github.com/risedle/monorepo/blob/733ae7b401ceed364151168d3237ed5bdcd54245/apps/interface/hooks/useFuseLeveragedTokenUserPosition.ts#L24-L28

So in stateless component, we need to handle state where `isLoaded = true` and `data=null` to display message such as "Wallet is not connected"

2022-08-01 04:46 UTC, pyk commented on apps/interface/tests/components/MySwapHistoryContainer.spec.tsx
> +// import QuoteBalanceContainer from "@/components/SwapCard/QuoteBalanceContainer";
remove this line

2022-08-01 04:46 UTC, pyk commented on apps/interface/tests/components/MySwapHistoryContainer.spec.tsx
> +describe("<QuoteBalanceContainer />", () => {
typo MySwapHistoryContainer

2022-08-01 04:46 UTC, pyk commented on apps/interface/tests/hooks/useFuseLeveragedTokenSwap.spec.ts
> +import useFuseLeveragedTokenUserPosition from "@/hooks/useFuseLeveragedTokenUserPosition";
remove unused imports

2022-08-01 04:46 UTC, pyk commented on apps/interface/tests/hooks/useFuseLeveragedTokenSwap.spec.ts
> +describe("useFuseLeveragedTokenUserPosition", () => {
typo

2022-08-01 04:46 UTC, pyk commented on apps/interface/tests/hooks/useFuseLeveragedTokenSwap.spec.ts
> +    describe("Given only symbol and address", () => {
typo: `Given symbol and address`

2022-08-01 04:48 UTC, pyk commented
@asaadam the build response from vercel is not helpful at all. Not sure what happen

```
Error [SyntaxError]: Unexpected token < in JSON at position 1480481
--
20:49:54.285 | at JSON.parse (<anonymous>)
20:49:54.285 | at Object.readConfigFile (/var/task/node_modules/@vercel/build-utils/dist/index.js:30773:29)
20:49:54.285 | at async Promise.all (index 1)
20:49:54.285 | at scanParentDirs (/var/task/node_modules/@vercel/build-utils/dist/index.js:31017:58)
20:49:54.285 | at getNodeVersion (/var/task/node_modules/@vercel/build-utils/dist/index.js:30975:29)
20:49:54.285 | at Object.build (/var/task/node_modules/@vercel/next/dist/index.js:42745:25)
20:49:54.285 | at doBuild (/var/task/node_modules/vercel/dist/index.js:239130:33)
20:49:54.285 | at main (/var/task/node_modules/vercel/dist/index.js:238956:16)
20:49:54.286 | at main (/var/task/node_modules/vercel/dist/index.js:246231:20)


```

2022-08-01 05:21 UTC, asaadam commented on apps/interface/hooks/useFuseLeveragedTokenSwap.ts
> +export function useFuseLeveragedTokenSwap(
should i rename filename too ?

2022-08-02 03:57 UTC, pyk requested changes

2022-08-02 03:57 UTC, pyk commented on apps/interface/hooks/useFuseLeveragedTokenMySwap.ts
> +        ? `https://api.risedle.com/v1/${symbol}/swaps/${userAddress}`
this should be `https://api.risedle.com/v1/${chainId}/flts/${symbol}/swaps/${userAddress}`

2022-08-08 05:24 UTC, pyk commented
@asaadam What's status of this pull request? we need to wait for the design right?

lets convert this to draft then

2022-08-08 11:36 UTC, asaadam commented
> @asaadam What's status of this pull request? we need to wait for the design right?
> 
> lets convert this to draft then

yap we still need to wait for the design ser

okay i will convert it to draft

2022-08-22 06:04 UTC, closed without merging