feat(apps/interface): support theming on rainbowkit
risedle/monorepo pull request #235
Opened 2022-08-07 11:53 UTC by asaadam

It's a bit verbose. 

but I cannot find a simpler solution for this.

2022-08-08 05:31 UTC, pyk requested changes

2022-08-08 05:31 UTC, pyk commented on apps/interface/pages/_app.tsx
> +                        theme={theme === "dark" ? darkTheme() : undefined}
@asaadam why we don't use `useColorMode` directly here? see example here https://github.com/risedle/monorepo/blob/540e6d0235b4594646416495ada46365d78cec2b/apps/interface/components/DarkmodeToggle/index.tsx#L7-L15

2022-08-08 11:35 UTC, asaadam commented on apps/interface/pages/_app.tsx
> +                        theme={theme === "dark" ? darkTheme() : undefined}
because it's outside of chakra provider ser 

CC: @math-marcellino

2022-08-08 11:36 UTC, asaadam commented on apps/interface/pages/_app.tsx
> +                        theme={theme === "dark" ? darkTheme() : undefined}
if you're okay with this implementation, i will continue to create test for this PR

2022-08-09 03:18 UTC, pyk commented on apps/interface/pages/_app.tsx
> +                        theme={theme === "dark" ? darkTheme() : undefined}
@asaadam please check my comment on linear issue. I think it's better to use container component so `useColorMode` can work

2022-08-09 04:04 UTC, asaadam commented on apps/interface/pages/_app.tsx
> +                        theme={theme === "dark" ? darkTheme() : undefined}
oh ya that solution also can be work. 
i will close this MR

2022-08-09 04:04 UTC, closed without merging