feat(apps/interface): setup darkmode and lightmode for rainbowkit
risedle/monorepo pull request #238
Opened 2022-08-09 02:05 UTC by math-marcellino

2022-08-09 06:20 UTC, math-marcellino commented
The test here failed because the coverage does not reach 95%. I was trying to create a test for this `RainbowKitContainer` component, but I kinda confused .-.
cc: @pyk

2022-08-09 06:35 UTC, pyk commented
@math-marcellino we need to increase the coverage for some components, let me create separate issue for this

2022-08-09 06:41 UTC, math-marcellino commented
> @math-marcellino we need to increase the coverage for some components, let me create separate issue for this

Got it sir, I've converted this PR to `ready for review`. Please kindly check, thank you!

2022-08-09 06:57 UTC, pyk commented
@math-marcellino we will merge this once we solve this issues:

- https://linear.app/risedle/issue/RIS-681/choreappsinterface-increase-code-coverage-for-darkmodetoggle

2022-08-10 10:08 UTC, pyk commented
@math-marcellino please merge `main` branch to this branch

2022-08-10 10:13 UTC, pyk requested changes
@math-marcellino let's move the Wagmi to the RainbowKitContainer too

https://github.com/risedle/monorepo/blob/988cee68f7f0ad5530b5dc7bc3014d515c8358c1/apps/interface/pages/_app.tsx#L23-L67

2022-08-16 04:31 UTC, pyk requested changes

2022-08-16 04:31 UTC, pyk commented on apps/interface/pages/_app.tsx
>  import "@rainbow-me/rainbowkit/styles.css";
@math-marcellino We need to move this to `RainbowKitContainer` too

2022-08-16 04:42 UTC, math-marcellino commented on apps/interface/pages/_app.tsx
>  import "@rainbow-me/rainbowkit/styles.css";
Ahh yes I forgot about that, lemme fix it now 👍

2022-08-16 04:50 UTC, pyk approved these changes
Thanks @math-marcellino

2022-08-16 04:52 UTC, merged