fix(interface/apps): fix color on trade pages
risedle/monorepo pull request #239
Opened 2022-08-09 04:36 UTC by asaadam

fix color on trade pages

refrence : https://www.figma.com/file/7Pzq1Gxxud84944o9kO2HM/Website-1.1?node-id=5%3A10525

2022-08-09 06:29 UTC, pyk requested changes
This changes only fix the light mode but break the dark mode color

2022-08-09 06:29 UTC, pyk commented on apps/interface/components/SwapHistoryCard/index.tsx
>      return (
add whitespace here

2022-08-09 06:29 UTC, pyk commented on apps/interface/components/SwapCard/index.tsx
> +            background={gray3}
This breaks the color on dark mode

2022-08-09 06:29 UTC, pyk commented on apps/interface/components/SwapCard/index.tsx
> +                            background: gray1,
This breaks the color on dark mode

2022-08-09 06:29 UTC, pyk commented on apps/interface/components/SwapCard/index.tsx
> +                            background: gray1,
This breaks the color on dark mode

2022-08-09 06:48 UTC, asaadam commented on apps/interface/components/SwapCard/index.tsx
> +            background={gray3}
ups i forgot to check color on dark mode. 
on it ser

2022-08-10 04:52 UTC, pyk commented
@asaadam This still break the darkmode

<img width="408" alt="Screen Shot 2022-08-10 at 11 51 07" src="https://user-images.githubusercontent.com/2213646/183818485-3bbd0014-89b7-4b46-ae0d-3a0c196c7b5f.png">
<img width="659" alt="Screen Shot 2022-08-10 at 11 51 14" src="https://user-images.githubusercontent.com/2213646/183818493-ae4bba8a-4e7d-4df4-b1e7-95969bc3c1db.png">


expected to be like this:

<img width="638" alt="Screen Shot 2022-08-10 at 11 52 01" src="https://user-images.githubusercontent.com/2213646/183818571-adb17917-2dfb-4958-9b7b-50789a296a0d.png">
<img width="382" alt="Screen Shot 2022-08-10 at 11 51 56" src="https://user-images.githubusercontent.com/2213646/183818577-be079863-e808-40e5-be3d-26be83ddf16e.png">

2022-08-10 05:30 UTC, pyk approved these changes
Thanks @asaadam  💯

2022-08-10 05:30 UTC, merged