feat(interface/apps): change icon svg and color
risedle/monorepo pull request #240
Opened 2022-08-09 05:04 UTC by asaadam

change icon svg and color

![image](https://user-images.githubusercontent.com/1397612/183568413-1112a3f0-379d-41de-ad74-d0e3aaf1f51c.png)

![image](https://user-images.githubusercontent.com/1397612/183568432-08274d06-a407-4d7b-92bc-c5339c6e4e0c.png)

2022-08-09 06:33 UTC, pyk requested changes

2022-08-09 06:33 UTC, pyk commented on apps/interface/components/Icons/ChainBSC.tsx
> +    const colorChain = useColorModeValue(
@asaadam We don't set the color here coz in some cases the icon requires different color. See product icon for example
<img width="274" alt="Screen Shot 2022-08-09 at 13 31 49" src="https://user-images.githubusercontent.com/2213646/183580268-cdc05ee2-75ca-4795-bbc0-1451bc0b94ee.png">

2022-08-09 06:33 UTC, pyk commented on apps/interface/components/Icons/ChainArbitrum.tsx
> +    const colorChain = useColorModeValue(
@asaadam We don't set the color here coz in some cases the icon requires different color. See product icon for example
<img width="274" alt="Screen Shot 2022-08-09 at 13 31 49" src="https://user-images.githubusercontent.com/2213646/183580268-cdc05ee2-75ca-4795-bbc0-1451bc0b94ee.png">

2022-08-09 06:33 UTC, pyk commented on apps/interface/components/Icons/ChainArbitrum.tsx
> +            fill={colorChain}
set fill to `currentColor`

2022-08-09 06:33 UTC, pyk commented on apps/interface/components/Icons/ChainBSC.tsx
> +            fill={colorChain}
remove fill and set fill to `path` and use `currentColor`

2022-08-09 06:46 UTC, asaadam commented on apps/interface/components/Icons/ChainBSC.tsx
> +    const colorChain = useColorModeValue(
ah i see, okay ser

2022-08-09 13:23 UTC, asaadam commented
@pyk do you know why the pipeline it's failing it's also happened on my another PR

2022-08-10 04:56 UTC, pyk commented
The BNBIcon is become breaking

<img width="161" alt="Screen Shot 2022-08-10 at 11 56 03" src="https://user-images.githubusercontent.com/2213646/183819028-76e0cfa8-905b-467d-b5d9-ac4f30056dd9.png">

2022-08-10 05:50 UTC, pyk requested changes

2022-08-10 05:50 UTC, pyk commented on apps/interface/components/ChainSwitcher/index.tsx
> +import { chain } from "wagmi";
Use `chainSlug` from `getBaseConfig` not from `wagmi`

2022-08-10 05:54 UTC, pyk approved these changes
Thanks @asaadam

2022-08-10 05:55 UTC, merged