feat(apps/interface) add my swap container
risedle/monorepo pull request #259
Opened 2022-08-14 03:59 UTC by asaadam

2022-08-16 04:35 UTC, pyk commented
@asaadam your implementation is different from the UI spec

<img width="631" alt="Screen Shot 2022-08-16 at 11 34 08" src="https://user-images.githubusercontent.com/2213646/184798675-9325edc9-c4bd-4401-841e-2bda03846df0.png">
<img width="754" alt="Screen Shot 2022-08-16 at 11 35 06" src="https://user-images.githubusercontent.com/2213646/184798683-839560cd-299c-4a91-a6b8-a80383db655a.png">

2022-08-16 04:51 UTC, pyk requested changes
see my comment above

2022-08-22 06:24 UTC, risedledev requested changes

2022-08-22 06:24 UTC, risedledev commented on apps/interface/components/SwapHistoryCard/Table.tsx
> +                    : `${transactionType} ${swap.tokenIn.symbol}`}
- buy

```
tokenOut = fltTokenSymbol
```

- sell

```
tokenIn = fltTokenSymbol
```

2022-08-26 03:33 UTC, pyk requested changes
The implementation is not same as designed by @ayikfour 

<img width="635" alt="Screen Shot 2022-08-26 at 10 29 10" src="https://user-images.githubusercontent.com/2213646/186811796-b1eac784-e600-47f6-9970-5876db5ce3ac.png">

expected:
<img width="559" alt="Screen Shot 2022-08-26 at 10 33 38" src="https://user-images.githubusercontent.com/2213646/186811929-4c5e2eac-0e17-4157-a7e9-2e0929521ad8.png">

2022-08-29 05:48 UTC, pyk requested changes
Smol nitpicks, otherwise LGTM. lets merge this

2022-08-29 05:48 UTC, pyk commented on apps/interface/components/SwapHistoryCard/Table.tsx
> +                            <Flex minH={"48px"} alignItems={"center"}>
@asaadam remove the `minH`

2022-08-29 05:48 UTC, pyk commented on apps/interface/components/SwapHistoryCard/Table.tsx
> +                            <Flex minH={"48px"} alignItems={"center"}>
@asaadam remove the `minH`

2022-08-29 13:57 UTC, pyk requested changes
Btw it seems that u miss another `minH`
<img width="630" alt="Screen Shot 2022-08-29 at 20 55 45" src="https://user-images.githubusercontent.com/2213646/187218137-fbcf7d86-ca0a-4f49-a8cd-cf967388350d.png">

2022-08-30 08:39 UTC, risedledev approved these changes
LGTM, kita deploy dulu yah @asaadam @math-marcellino

2022-08-30 08:40 UTC, pyk approved these changes

2022-08-30 08:40 UTC, merged