[RIS-721] Create new router & controller for FLTs gain data
risedle/monorepo pull request #263
Opened 2022-08-24 03:16 UTC by math-marcellino

1. Rename endpoint path from `/v1/{chainId}/flts/gains` to `/v1/{chainId}/flts/insight/gain` => because the first one have conflict with `/v1/{chainId}/flts/{symbol}`
2. Create router and controller for gains data
3. Use dummy service function to generate data

2022-08-24 04:15 UTC, pyk commented
@math-marcellino btw, please create new controller and service inside `flt` directory. 

For example: 
- https://github.com/risedle/monorepo/tree/main/apps/api/src/controllers/flt
- https://github.com/risedle/monorepo/tree/main/apps/api/src/services/flt

2022-08-24 04:35 UTC, math-marcellino commented
> @math-marcellino btw, please create new controller and service inside `flt` directory.
> 
> For example:
> 
> * https://github.com/risedle/monorepo/tree/main/apps/api/src/controllers/flt
> * https://github.com/risedle/monorepo/tree/main/apps/api/src/services/flt

Okay sir, I've separated the controller and service in different file. Please kindly check again sir @pyk , thank you!

2022-08-24 05:17 UTC, pyk requested changes

2022-08-24 05:17 UTC, pyk commented on apps/api/src/services/flt/GetFuseLeveragedTokensGains.ts
> +    if (chainId) {
@math-marcellino no need to add if here, just return the array directly

2022-08-24 05:48 UTC, asaadam commented on apps/api/src/services/flt/GetFuseLeveragedTokensGains.ts
> +    if (chainId) {
i will fix it ser, it's part of my task

2022-08-24 08:49 UTC, math-marcellino commented on apps/api/src/services/flt/GetFuseLeveragedTokensGains.ts
> +const queryFuseLeveragedTokenSwapsBySymbol = gql`
@asaadam I think this one should be named like `queryFuseLeveragedTokenPriceData`(?)
cc: @pyk CMIIW

2022-08-24 17:13 UTC, pyk commented on apps/api/src/services/flt/GetFuseLeveragedTokensGains.ts
> +const queryFuseLeveragedTokenSwapsBySymbol = gql`
Yes, sorry missed this one @math-marcellino

2022-08-24 17:15 UTC, pyk requested changes
`queryFuseLeveragedTokenSwapsBySymbol` update to `queryFuseLeveragedTokenPriceData `

2022-08-25 07:48 UTC, pyk commented
@math-marcellino @asaadam it seems the openapi spec is broken

<img width="1449" alt="Screen Shot 2022-08-25 at 14 45 54" src="https://user-images.githubusercontent.com/2213646/186606181-072e87e5-00b7-4a80-95b6-5b305619ba8b.png">

expected to be like this
<img width="1475" alt="Screen Shot 2022-08-25 at 14 46 48" src="https://user-images.githubusercontent.com/2213646/186606293-aabda799-c9c3-4ad9-95f1-1a75523f5ac3.png">

Is there any problem when u run the api locally? I can't find the issue on the new spec

You can try the staging version here https://apiedge.risedle.exchange/#/Insight%20Generator/get_v1__chainId__flts_insight_gains

2022-08-25 07:56 UTC, pyk requested changes
Please update the `openapi.yml` to the following:

```yml
openapi: 3.0.3

info:
  title: Risedle API
  version: 1.1.0

servers:
  - description: Staging
    url: https://apiedge.risedle.exchange
  - description: Production
    url: https://api.risedle.exchange
  - description: Local
    url: http://localhost:3000

tags:
  - name: Fuse Leveraged Token
    description: List of endpoint for Fuse Leveraged Token

paths:
  /v1/{chainId}/flts:
    get:
      tags:
        - Fuse Leveraged Token
      operationId: GetFuseLeveragedTokensByChainId
      summary: |
        Get list of Fuse Leveraged Tokens on specific chain
      parameters:
        - in: path
          name: chainId
          schema:
            $ref: "#/components/schemas/ChainId"
          required: true
      responses:
        200:
          description: |
            List of Fuse Leveaged Token and the market information
          content:
            application/json:
              schema:
                type: object
                properties:
                  tokens:
                    type: array
                    items:
                      $ref: "#/components/schemas/FuseLeveragedTokenInfo"
        404:
          description: Chain ID not supported
        500:
          description: Internal server error

  /v1/{chainId}/flts/{symbol}:
    get:
      tags:
        - Fuse Leveraged Token
      operationId: GetFuseLeveragedTokenBySymbol
      summary: Get Fuse Leveraged Token by symbol
      parameters:
        - in: path
          name: chainId
          schema:
            $ref: "#/components/schemas/ChainId"
          required: true
        - in: path
          name: symbol
          schema:
            type: string
          example: "ETHRISE"
          required: true
      responses:
        200:
          description: Fuse Leveraged Token info.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FuseLeveragedTokenInfo"
        404:
          description: Chain ID not supported
        500:
          description: Internal server error

  /v1/{chainId}/flts/{symbol}/charts:
    get:
      tags:
        - Fuse Leveraged Token
      operationId: GetFuseLeveragedTokenChartsBySymbol
      summary: |
        Get Fuse Leveraged Token's historical prices, volumes and fees by symbol
      parameters:
        - in: path
          name: chainId
          schema:
            $ref: "#/components/schemas/ChainId"
          required: true
        - in: path
          name: symbol
          schema:
            type: string
          example: "ETHRISE"
          required: true
      responses:
        200:
          description: Fuse Leveraged Token charts data
          content:
            application/json:
              schema:
                type: object
                properties:
                  prices:
                    type: array
                    items:
                      $ref: "#/components/schemas/FuseLeveragedTokenPrice"
                  volumes:
                    type: array
                    items:
                      $ref: "#/components/schemas/FuseLeveragedTokenVolume"
                  fees:
                    type: array
                    items:
                      $ref: "#/components/schemas/FuseLeveragedTokenFee"
        404:
          description: Chain ID not supported
        500:
          description: Internal server error

  /v1/{chainId}/flts/{symbol}/swaps:
    get:
      tags:
        - Fuse Leveraged Token
      operationId: GetFuseLeveragedTokenSwapsBySymbol
      summary: |
        Get Fuse Leveraged Token's historical swaps by symbol and user address (optional)
      parameters:
        - in: path
          name: chainId
          schema:
            $ref: "#/components/schemas/ChainId"
          required: true
        - in: path
          name: symbol
          schema:
            type: string
          example: "ETHRISE"
          required: true
        - in: query
          name: userAddress
          schema:
            type: string
          example: "0x1418be4753a22b69b613fa8b8144d856c023d46b"
      responses:
        200:
          description: Fuse Leveraged Token swaps data
          content:
            application/json:
              schema:
                type: object
                properties:
                  flt:
                    type: array
                    items:
                      $ref: "#/components/schemas/FuseLeveragedTokenSwap"
                  user:
                    type: array
                    items:
                      $ref: "#/components/schemas/FuseLeveragedTokenSwap"
        404:
          description: Chain ID not supported
        500:
          description: Internal server error

  /v1/{chainId}/flts/{symbol}/backings:
    get:
      tags:
        - Fuse Leveraged Token
      operationId: GetFuseLeveragedTokenBackingsBySymbol
      summary: |
        Get Fuse Leveraged Token's historical backings by symbol
      parameters:
        - in: path
          name: chainId
          schema:
            $ref: "#/components/schemas/ChainId"
          required: true
        - in: path
          name: symbol
          schema:
            type: string
          example: "ETHRISE"
          required: true
      responses:
        200:
          description: Fuse Leveraged Token backings data
          content:
            application/json:
              schema:
                type: object
                properties:
                  backings:
                    type: array
                    items:
                      $ref: "#/components/schemas/FuseLeveragedTokenBacking"
        404:
          description: Chain ID not supported
        500:
          description: Internal server error

  /v1/{chainId}/positions/{positionId}:
    get:
      tags:
        - Fuse Leveraged Token
      operationId: GetFuseLeveragedTokenUserOpenPosition
      summary: |
        Get user's open position by the position ID
      parameters:
        - in: path
          name: chainId
          schema:
            $ref: "#/components/schemas/ChainId"
          required: true
        - in: path
          name: positionId
          description: "user address - flt address"
          schema:
            type: string
          example: "0x1418be4753a22b69b613fa8b8144d856c023d46b-0x4f7255178b8f15c2cbe92d09b8a77b53ef4ec9ea"
          required: true
      responses:
        200:
          description: User's open position
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FuseLeveragedTokenUserOpenPosition"
        404:
          description: Chain ID not supported
        500:
          description: Internal server error

  /v1/{chainId}/flts/insight/gains:
    get:
      tags:
        - Insight Generator
      operationId: GetFuseLeveragedTokensGains
      summary: |
        Get daily and weekly FLTs gains
      parameters:
        - in: path
          name: chainId
          schema:
            $ref: "#/components/schemas/ChainId"
          required: true
      responses:
        200:
          description: Fuse Leveraged Tokens gains data
          content:
            application/json:
              schema:
                type: object
                properties:
                  tokens:
                    type: array
                    items:
                      $ref: "#/components/schemas/FuseLeveragedTokenGains"
        404:
          description: Chain ID not supported
        500:
          description: Internal server error

components:
  schemas:
    Address:
      description: 20 byte Ethereum address encoded as a hex with `0x` prefix
      type: string
      example: "0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8"

    BigNumber:
      description: Ethers.js BigNumber
      type: string
      example: "1000000000"

    ChainId:
      description: Chain ID
      type: number
    [...]

2022-08-25 07:57 UTC, pyk commented
Turns out there is some typos on the `openapi.yml` spec

Feel free to use https://editor-next.swagger.io/ to check the error

2022-08-25 08:26 UTC, math-marcellino commented
> Turns out there is some typos on the `openapi.yml` spec
> 
> Feel free to use https://editor-next.swagger.io/ to check the error

Ahh I see, okay I'll fix it sir, tysm!

2022-08-25 11:59 UTC, pyk requested changes

2022-08-25 11:59 UTC, pyk commented on apps/api/src/services/flt/GetFuseLeveragedTokensGains.ts
> +                timestmap: periodStartUnix
typo, this should be `timestamp`

2022-08-25 11:59 UTC, pyk commented on apps/api/src/services/flt/GetFuseLeveragedTokensGains.ts
> +                timestmap: periodStartUnix
typo, this should be `timestamp`

2022-08-25 11:59 UTC, pyk commented on apps/api/src/services/flt/GetFuseLeveragedTokensGains.ts
> +    timestmap: number;
typo, this should be `timestamp`

2022-08-25 12:02 UTC, math-marcellino commented on apps/api/src/services/flt/GetFuseLeveragedTokensGains.ts
> +    timestmap: number;
Both fixed sir 👍

2022-08-25 15:03 UTC, pyk approved these changes
LGTM @math-marcellino @asaadam

2022-08-25 15:04 UTC, merged