chore(apps/interface): refactor IndexPage imports
risedle/monorepo pull request #348
Opened 2022-09-20 14:20 UTC by asaadam

Copy paste the following markdown in the pull request

## Scope
List of affected projects:

- apps/interface

## Description
We need to use default import for all imported components and utilities in [IndePage][1].

[1]: https://github.com/risedle/monorepo/blob/main/apps/interface/pages/index.tsx#L4-L15

## Action items
Action items for this pull request:

- [X] Update `import {x} from "y"` to `import x from y`

## Checklist
You should check this before requesting for review:

- [X] Branch name use the the following format RIS-{NUMBER}
- [X] Pull request title is "chore(apps/interface): refactor IndexPage imports"
- [X] Make sure new files are 100% covered in [Risedle Code Coverage](https://coverage.risedle.com)

2022-09-20 15:03 UTC, pyk requested changes
Just smol nits @asaadam

2022-09-20 15:03 UTC, pyk commented on apps/interface/components/HomeHeading/index.tsx
> +export default HomeHeading;
We need to remove the individual export in this component.

Replace:

```ts
export const HomeHeading = ...
```

with:

```
const HomeHeading = ...
```

2022-09-20 15:03 UTC, pyk commented on apps/interface/components/TokenCard/cards.tsx
> +export default TokenCards;
We need to remove the individual export in this component.

Replace:

```ts
export const TokenCards = ...
```

with:

```
const TokenCards = ...
```

2022-09-20 15:03 UTC, pyk commented on apps/interface/components/WarningBar/index.tsx
> +export default WarningBar;
We need to remove the individual export in this component.

Replace:

```ts
export const WarningBar = ...
```

with:

```ts
const WarningBar = ...
```

2022-09-20 15:03 UTC, pyk commented on apps/interface/utils/fetchFuseLeveragedTokens.ts
> +export default fetchFuseLeveragedTokens;
We need to remove the individual export in this utils.

Replace:

```ts
export const fetchFuseLeveragedTokens = ...
```

with:

```ts
const fetchFuseLeveragedTokens = ...
```

2022-09-20 15:03 UTC, pyk commented on apps/interface/utils/getFuseLeveragedTokensSummary.ts
> +export default getFuseLeveragedTokensSummary;
We need to add whitepsace above this line

Then Replace:

```ts
export const getFuseLeveragedTokensSummary = ...
```

with:

```ts
const getFuseLeveragedTokensSummary = ...
```

2022-09-20 15:21 UTC, asaadam commented
@pyk if we do that, we should change the test file too, it's that okay?

2022-09-20 15:30 UTC, pyk commented
@asaadam yes lets update the imports in the test too

2022-09-21 09:58 UTC, pyk approved these changes
Thanks @asaadam !

2022-09-21 09:58 UTC, merged