chore(apps/interface): add concurrency flag to workflow
risedle/monorepo pull request #369
Opened 2022-09-26 01:45 UTC by math-marcellino

## Scope
List of affected projects:

- apps/interface

## Description
We want to be able to merge apps/interface change to main branch without
waiting the deployment finished.

In order to do that, we need to add concurrency in the `apps-interface-stag.yml`
and `apps-interface-prod.yml` github workflow.

```yaml
concurrency: interface
```

## Action items
Action items for this pull request:

- [ ] Add `concurrency` to `apps-interface-stag.yml`
- [ ] Add `concurrency` to `apps-interface-prod.yml`

## Checklist
You should check this before requesting for review:

- [ ] Branch name use the the following format RIS-{NUMBER}
- [ ] Pull request title is "chore(apps/interface): add concurrency flag to workflow"
- [ ] Make sure new files are 100% covered in [Risedle Code Coverage](https://coverage.risedle.com)

2022-09-26 01:47 UTC, math-marcellino commented
Gm sir @pyk, actually I'm not really sure if I put the `concurrency` in the right place inside the file .-.

So please let me know if it's wrong, thank you!

2022-09-26 11:44 UTC, pyk commented
@math-marcellino btw, we need to define `concurrency` below the `name`

2022-09-26 11:44 UTC, pyk requested changes
define `concurrency` below the `name`

2022-09-30 08:45 UTC, pyk approved these changes
Thanks @math-marcellino , LGTM!

2022-09-30 08:47 UTC, merged