chore(apps/interface): refactor PriceChart
risedle/monorepo pull request #388
Opened 2022-10-07 00:51 UTC by math-marcellino

## Scope
List of affected projects:

- apps/interface

## Description

We need to refactor the `PriceChart` component.
First we need to use default import for all subcomponents.
We may also need to refactor all sub components to use default export.

## Action items
Action items for this pull request:

- [ ] Use default import for all sub-components
- [ ] Remove default export for PriceChart and all sub-components

## Checklist
You should check this before requesting for review:

- [ ] Branch name use the the following format RIS-{NUMBER}
- [ ] Pull request title is "chore(apps/interface): refactor PriceChart"
- [ ] Make sure CSS styling is same as the spec (padding, border etc)
- [ ] Make sure new files are 100% covered in [Risedle Code Coverage](https://coverage.risedle.com)

2022-10-10 16:00 UTC, pyk requested changes
Smol nits @math-marcellino

2022-10-10 16:00 UTC, pyk commented on apps/interface/components/PriceChart/index.tsx
> +import PriceChartLine, { PriceChartLineProps } from "./Line";
@math-marcellino import interface as type:

```
import type { PriceChartLineProps } from "./Line";
import PriceChartLine from "./Line";
```

2022-10-10 17:23 UTC, math-marcellino commented on apps/interface/components/PriceChart/index.tsx
> +import PriceChartLine, { PriceChartLineProps } from "./Line";
fixed sir.

Btw sorry the commits for this PR are not verified because I forgot to setup the gpg on my WSL hehe. My commits will be verified in the coming PR sir 👍

2022-10-11 03:00 UTC, pyk approved these changes
LGTM @math-marcellino

2022-10-11 03:01 UTC, merged