chore(apps/interface): increase coverage for InsightImageDOM
risedle/monorepo pull request #395
Opened 2022-10-08 15:12 UTC by asaadam

## Scope
List of affected projects:

- apps/interface

## Description
We need to increase the test coverage for `components/InsightImageDOM/index.tsx`

See the recent coverage here https://coverage.risedle.com/apps/interface/coverage/lcov-report/components/InsightImageDOM/index.tsx.html

you will notice that the following function is not covered yet:

```typescript
// Given html element and filename, export html element to downloadble filename
export async function exportImage(
    element: HTMLElement | null,
    filename: string
): Promise<void> {
    if (element) {
        const result = await domtoimage.toJpeg(element);
        const link = document.createElement("a");
        link.className = "download-helper";
        link.download = filename;
        link.href = result;
        link.click();
    } else {
        alert("Element is null");
    }
}
```

and also `InsightImageDOM` is not rendered with `timestamp=undefined` yet on the test.

So we need to update https://github.com/risedle/monorepo/blob/main/apps/interface/tests/components/InsightImageDom.spec.tsx
to test `exportImage` with element defined and null.

Then we also need to render `InsightImageDOM` and mock `useGetInsight` to return dailyGain.timestamp as undefined.

## Action items
Action items for this pull request:

- [X] Add `exportImage` test to `InsightImageDOM` test 
- [X] Add case where `useGetInsight` returns undefined timestamp when render

## Checklist
You should check this before requesting for review:

- [X] Branch name use the the following format RIS-{NUMBER}
- [X] Pull request title is "chore(apps/interface): increase coverage for InsightImageDOM"
- [X] Make sure CSS styling is same as the spec (padding, border etc)
- [X] Make sure new files are 100% covered in [Risedle Code Coverage](https://coverage.risedle.com)

2022-10-11 03:03 UTC, pyk requested changes
Smol nits @asaadam

2022-10-11 03:03 UTC, pyk commented on apps/interface/components/InsightImageDOM/index.tsx
> +            console.log(data);
@asaadam remove this

2022-10-12 23:25 UTC, pyk commented on apps/interface/components/InsightImageDOM/index.tsx
> +            console.log(data);
@asaadam ping

2022-10-13 15:12 UTC, asaadam commented on apps/interface/components/InsightImageDOM/index.tsx
> +            console.log(data);
updated ser

2022-12-06 10:41 UTC, closed without merging