chore(apps/interface): increase coverage for SellCTAContainer
risedle/monorepo pull request #397
Opened 2022-10-11 10:30 UTC by math-marcellino

## Scope
List of affected projects:

- apps/interface

## Description

We need to increase the test coverage for the `SellCTAContainer` component.

First we need to create new file:

```
tests/components/SwapCard/SellCTAContainer.spec.tsx
```

Here is the test case that we need to add to the test:
1. Given `amount = ""`, button `data-testid="CTAEnterAmountButton"` should be rendered.
2. Given `data == null || (data && data[0] == null)`, button `data-testid="CTALoadingButton"` should be rendered.
3. Given `amountIn.gt(userBalance)`, button `data-testid="CTANotEnoughBalanceButton"` should be rendered.
6. Given `waitApproval.isLoading`, button `data-testid="CTAApprovingButton"` should be rendered
7. Given `amountIn.gte(allowanceAmount)`, button `data-testid="CTAApprovalButton"` should be rendered
8. Given `waitSell.isLoading`, button `data-testid="CTASwappingButton"` should be rendered.
9. Given non of the case above, button `data-testid="CTASwapButton"` shoukd be rendered.

Please note that you may need to mock the following hooks:

1. `useBuyAmountStore` to simulate the `amount` 
2. `useContractReads` to simulate the `data`

## Action items
Action items for this pull request:

- [ ] Create new test file
- [ ] Add test

## Checklist
You should check this before requesting for review:

- [ ] Branch name use the the following format RIS-{NUMBER}
- [ ] Pull request title is "chore(apps/interface): increase coverage for SellCTAContainer"
- [ ] Make sure CSS styling is same as the spec (padding, border etc)
- [ ] Make sure new files are 100% covered in [Risedle Code Coverage](https://coverage.risedle.com)

2022-10-11 11:09 UTC, pyk requested changes

2022-10-11 11:09 UTC, pyk commented on apps/interface/tsconfig.json
> +        "next-env.d.ts",
@math-marcellino it seems that Cloudflare Worker types is not picked by the TypeScript compiler. 

Add `worker.d.ts` here.

2022-10-11 11:19 UTC, math-marcellino commented on apps/interface/tsconfig.json
> +        "next-env.d.ts",
Done sir, but seems like the build process still failed .-.

2022-10-12 04:03 UTC, pyk commented on apps/interface/tsconfig.json
> +        "next-env.d.ts",
@math-marcellino I think we need to add the following directory to `exclude` fields in `tsconfig.json`:

- router
- controllers
- templates
- atoms
- molecules
- organisms

2022-10-12 10:38 UTC, closed without merging